language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
  - "4"
  - "6"
  - "8"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run test
  - npm run report-coverage
  - npm run build
